### ISSUE TITLE
[PE-D][Tester D] Wrong GUI displayed in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-1/tp#139]
GUI in UG
![image.png](https://raw.githubusercontent.com/weeweh/ped/main/files/52d5342d-048e-4f62-abba-d6cca8ed0876.png)

GUI in jar
![image.png](https://raw.githubusercontent.com/weeweh/ped/main/files/6e5a92f4-c3d9-4565-8c1a-8c4865ed92eb.png)

Patients should not have their illness displayed in this tab

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: weeweh/ped#1

**Comment by lyuanww** [comment]
fix SampleDataUtil.java
