### ISSUE TITLE
[PE-D][Tester C] Typing in an invalid time does not give any prompt or warning in the edit command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-1/tp#146]
![Screenshot 2023-11-03 at 4.28.09 PM.png](https://raw.githubusercontent.com/lsyurea/ped/main/files/c709cd3a-6cb3-4d0e-9a75-c8f0306926c5.png)

Pressing enter does not give any warning to the user that it is supposed to be 16:00 instead of 1600. While the correct usage is specified in the user guide, exceptions should still be handled due to user navigability issues. Here, it is common practice to show invalid command warning to user.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: lsyurea/ped#5

**Comment by tanboonkhong** [comment]
Add error message
