### ISSUE TITLE
[PE-D][Tester B] Issues for duplicate appts and med history

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-1/tp#147]
When trying to add duplicate appointment time, for the same patient, the UI is unresponsive. The error in terminal says that this is due to duplicates. 

However, when list-appointments is ran, all the previously added duplicate appts are displayed.

Same problem for medical history

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: jack1e0/ped#3

**Comment by lyuanww** [comment]
Check with implementation. Will fix
