### ISSUE TITLE
[PE-D][Tester D] Inconsistent constraints on phone number 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F08-1/tp#149]
![image.png](https://raw.githubusercontent.com/weeweh/ped/main/files/c656c457-f8f0-443b-a4fc-d55a3f47634b.png)

Error message suggest phone number more than 3 digits long but UG suggests phone number to be strictly 8 digits 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: weeweh/ped#6

**Comment by lyuanww** [comment]
Fix validation for phone number
