### ISSUE TITLE
[PE-D][Tester D] Delete-appt not specific in usage

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-1/tp#158]
no clue how to use patient index

![image.png](https://raw.githubusercontent.com/weeweh/ped/main/files/4853ca54-f7c8-4743-85b9-3b9f8f0ef652.png)

inputting another patient index does not give allow user to execute command/press enter

Not too sure if user should be remembering the patients' index in the patients list before doing any appointment command. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: weeweh/ped#11

**Comment by lyuanww** [comment]
Will add more clear instructions in UG
