### ISSUE TITLE
[PE-D][Tester C] Non-uniform command style

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-1/tp#163]
![Screenshot 2023-11-03 at 7.59.52 PM.png](https://raw.githubusercontent.com/lsyurea/ped/main/files/c08061b6-1d0c-4265-83ed-25e43fd7ade1.png)

Appointment is spelt in full for list-appointments but not for edit-appt.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: lsyurea/ped#13

**Comment by lyuanww** [comment]
Will update in Planned Enhancements in DG
