### ISSUE TITLE
[PE-D][Tester C] edit-medical-history does not detect changes in pi

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F08-1/tp#165]
![Screenshot 2023-11-03 at 8.10.05 PM.png](https://raw.githubusercontent.com/lsyurea/ped/main/files/50e259d0-b3cf-4763-b5e5-fc69ebdf5453.png)

When I try to edit medical history 1 tagged to person index 1 to person index 2, it does not work and does not give me any error message. However, an exception is shown in terminal. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: lsyurea/ped#15

**Comment by lyuanww** [comment]
Users are not allowed to do this. Will specify it in UG
