### ISSUE TITLE
[PE-D][Tester C] No exception handling for the wrong pi in delete-medical-history

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F08-1/tp#167]
![Screenshot 2023-11-03 at 8.14.20 PM.png](https://raw.githubusercontent.com/lsyurea/ped/main/files/f8f6128e-7362-443c-ab81-03b18b7ad3d3.png)

Nothing happens when I press enter until I realised that the medical history 1 is tagged to person 1 instead of person 2. Only the terminal shows that an exception has occured.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: lsyurea/ped#17

**Comment by tanboonkhong** [comment]
Incorrect error message, should be functionality bug
