### ISSUE TITLE
[PE-D][Tester A] Add Medical History Documentation bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F08-1/tp#169]
Should specify what the date is. Is it the diagnosed date, or is it the date that the clinic is informed? The description given is very vague.

![image.png](https://raw.githubusercontent.com/cheeggered/ped/main/files/c00b72b9-d261-4446-b005-7ce256c2c417.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: cheeggered/ped#5

**Comment by lyuanww** [comment]
Fix UG
