### ISSUE TITLE
Update DG

### ISSUE THREAD

**Issue by lyuanww** [AY2324S1-CS2103T-F08-1/tp#98]

**Comment by lyuanww** [comment]
Time to use PlantUML and draw diagrams

**Comment by pangyyen** [comment]
follow [this link](https://se-education.org/guides/tutorials/plantUml.html) to from the 2103 website to create UML diagrams using plugin in IntelliJ

**Comment by pangyyen** [comment]
- Can look up for the detailed requirements in the website: [tP: deliverables](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-deliverables.html#deliverable-developer-guide-dg)
- Image below shows the path/folder to store the UML diagrams, i.e.save as `.puml` and save them in `docs/diagrams`
<img width="694" alt="image" src="https://github.com/AY2324S1-CS2103T-F08-1/tp/assets/122292114/9506b974-24d4-49c7-8d21-11d8b9a6aed0">
